version: 2
updates:
  - package-ecosystem: npm
    directory: /render
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      types:
        patterns:
          - "@types/*"
      dev:
        dependency-type: development
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      actions:
        patterns:
          - "*"
