sonar.organization=thisisnacho
sonar.projectKey=sonarqube-multi-project-comment
sonar.projectName=sonarqube-multi-project-comment

sonar.sources=render/src
sonar.exclusions=render/dist/**,examples/**

sonar.typescript.tsconfigPath=render/tsconfig.json
sonar.sourceEncoding=UTF-8
