import { describe, expect, it } from "vitest";
import { parseReportTask, stripTrailingSlash } from "./sonar.js";

describe("stripTrailingSlash", () => {
  it("removes a single trailing slash", () => {
    expect(stripTrailingSlash("https://example.com/")).toBe("https://example.com");
  });

  it("removes multiple trailing slashes", () => {
    expect(stripTrailingSlash("https://example.com///")).toBe("https://example.com");
  });

  it("leaves a string without trailing slashes alone", () => {
    expect(stripTrailingSlash("https://example.com/path")).toBe("https://example.com/path");
  });

  it("handles the empty string", () => {
    expect(stripTrailingSlash("")).toBe("");
  });

  it("handles a string of only slashes", () => {
    expect(stripTrailingSlash("////")).toBe("");
  });
});

describe("parseReportTask", () => {
  const sample = `
projectKey=my-project
serverUrl=https://sonar.example.com
serverVersion=10.5
dashboardUrl=https://sonar.example.com/dashboard?id=my-project
ceTaskId=task-abc-123
ceTaskUrl=https://sonar.example.com/api/ce/task?id=task-abc-123
`.trim();

  it("parses all key=value pairs", () => {
    const task = parseReportTask(sample);
    expect(task).toEqual({
      projectKey: "my-project",
      serverUrl: "https://sonar.example.com",
      dashboardUrl: "https://sonar.example.com/dashboard?id=my-project",
      ceTaskId: "task-abc-123",
      ceTaskUrl: "https://sonar.example.com/api/ce/task?id=task-abc-123",
    });
  });

  it("ignores comment lines", () => {
    const withComments = `# generated by scanner\nprojectKey=p\nceTaskId=t\n# end`;
    expect(parseReportTask(withComments).projectKey).toBe("p");
  });

  it("throws when projectKey is missing", () => {
    expect(() => parseReportTask("ceTaskId=t")).toThrow(/projectKey/);
  });

  it("throws when ceTaskId is missing", () => {
    expect(() => parseReportTask("projectKey=p")).toThrow(/ceTaskId/);
  });

  it("handles CRLF line endings", () => {
    const crlf = "projectKey=p\r\nceTaskId=t\r\n";
    expect(parseReportTask(crlf)).toMatchObject({ projectKey: "p", ceTaskId: "t" });
  });
});
